# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Running Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command: ["Formatting and Linting", "Svelte check", "Vitest", "Playwright"]

    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: kudadam
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Creating env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          file_name: .env.production
          envkey_MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          envkey_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          envkey_MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - if: matrix.command == 'Formatting and Linting'
        name: "Formatting and Linting Code"
        run: |
          pnpm format
          pnpm lint

      - if: matrix.command == 'Svelte Check'
        name: "Running Svelte Check"
        run: pnpm check

      - if: matrix.command == 'Vitest'
        name: "Running Vitest tests"
        run: pnpm test:unit

      - if: matrix.command == 'Playwright'
        name: "Installing Playwright dependencies && Running Tests"
        run: |
          pnpx playwright install
          pnpm test
